#! /bin/bash
set -x

rm -rf config.guess config.log config.status config.sub configure stamp-h*
pushd autom4te.cache
rm -f output.0 requests traces.0
popd

touch config-h.in NEWS README ChangeLog
/usr/bin/aclocal -I config
libtoolize --force --copy
libtoolize --force --copy --ltdl
/usr/bin/autoheader
#add --include-deps if you want to bootstrap with any other compiler than gcc
#automake --add-missing --copy --include-deps
/usr/bin/autoconf
/usr/bin/automake --add-missing --copy
# rm -f config.cache
export CXX=g++3
./configure --exec-prefix=/usr --prefix=/usr --with-boost-location=/usr/include/boost/ 
#--with-stl-location=/usr/lib/gcc-lib/i686-pc-linux-gnu/3.3.2/include/g++-v3/
chmod +x matisrti
alias make='make > /dev/null'
#--enable-proj
# make clean
# make dist
