// Copyright 2001, 2002 Commonwealth of Australia
// Authors: John Wharington, David Andrews, Peter Beckwith, Nicholas Hynes
// Defence Science Technology Organisation, Maritime Platforms Division
// CVS $RCSfile: MATIS_LibHookup_SymbolTable_w32_hookenum.cpp,v $
// CVS $Date: 2005/11/11 04:51:13 $
// CVS $Revision: 1.1.1.1 $





enum {

    KERNEL32_LoadLibraryA = 0,
    KERNEL32_LoadLibraryW = 1,
    KERNEL32_LoadLibraryExA = 2,
    KERNEL32_LoadLibraryExW = 3,
    DLL_RTI__RTIambassador__associateRegionForUpdates3 = 4,
    DLL_RTI__RTIambassador__attributeOwnershipAcquisition3 = 5,
    DLL_RTI__RTIambassador__attributeOwnershipAcquisitionIfAvailable2 = 6,
    DLL_RTI__RTIambassador__attributeOwnershipReleaseResponse2 = 7,
    DLL_RTI__RTIambassador__cancelAttributeOwnershipAcquisition2 = 8,
    DLL_RTI__RTIambassador__cancelNegotiatedAttributeOwnershipDivestiture2 = 9,
    DLL_RTI__RTIambassador__changeAttributeOrderType3 = 10,
    DLL_RTI__RTIambassador__changeAttributeTransportationType3 = 11,
    DLL_RTI__RTIambassador__changeInteractionOrderType2 = 12,
    DLL_RTI__RTIambassador__changeInteractionTransportationType2 = 13,
    DLL_RTI__RTIambassador__createFederationExecution2 = 14,
    DLL_RTI__RTIambassador__createRegion2 = 15,
    DLL_RTI__RTIambassador__deleteObjectInstance3 = 16,
    DLL_RTI__RTIambassador__deleteObjectInstance2 = 17,
    DLL_RTI__RTIambassador__deleteRegion1 = 18,
    DLL_RTI__RTIambassador__destroyFederationExecution1 = 19,
    DLL_RTI__RTIambassador__disableAsynchronousDelivery0 = 20,
    DLL_RTI__RTIambassador__disableAttributeRelevanceAdvisorySwitch0 = 21,
    DLL_RTI__RTIambassador__disableAttributeScopeAdvisorySwitch0 = 22,
    DLL_RTI__RTIambassador__disableClassRelevanceAdvisorySwitch0 = 23,
    DLL_RTI__RTIambassador__disableInteractionRelevanceAdvisorySwitch0 = 24,
    DLL_RTI__RTIambassador__disableTimeConstrained0 = 25,
    DLL_RTI__RTIambassador__disableTimeRegulation0 = 26,
    DLL_RTI__RTIambassador__enableAsynchronousDelivery0 = 27,
    DLL_RTI__RTIambassador__enableAttributeRelevanceAdvisorySwitch0 = 28,
    DLL_RTI__RTIambassador__enableAttributeScopeAdvisorySwitch0 = 29,
    DLL_RTI__RTIambassador__enableClassRelevanceAdvisorySwitch0 = 30,
    DLL_RTI__RTIambassador__enableInteractionRelevanceAdvisorySwitch0 = 31,
    DLL_RTI__RTIambassador__enableTimeConstrained0 = 32,
    DLL_RTI__RTIambassador__enableTimeRegulation2 = 33,
    DLL_RTI__RTIambassador__federateRestoreComplete0 = 34,
    DLL_RTI__RTIambassador__federateRestoreNotComplete0 = 35,
    DLL_RTI__RTIambassador__federateSaveBegun0 = 36,
    DLL_RTI__RTIambassador__federateSaveComplete0 = 37,
    DLL_RTI__RTIambassador__federateSaveNotComplete0 = 38,
    DLL_RTI__RTIambassador__flushQueueRequest1 = 39,
    DLL_RTI__RTIambassador__getAttributeHandle2 = 40,
    DLL_RTI__RTIambassador__getAttributeName2 = 41,
    DLL_RTI__RTIambassador__getAttributeRoutingSpaceHandle2 = 42,
    DLL_RTI__RTIambassador__getDimensionHandle2 = 43,
    DLL_RTI__RTIambassador__getDimensionName2 = 44,
    DLL_RTI__RTIambassador__getInteractionClassHandle1 = 45,
    DLL_RTI__RTIambassador__getInteractionClassName1 = 46,
    DLL_RTI__RTIambassador__getInteractionRoutingSpaceHandle1 = 47,
    DLL_RTI__RTIambassador__getObjectClass1 = 48,
    DLL_RTI__RTIambassador__getObjectClassHandle1 = 49,
    DLL_RTI__RTIambassador__getObjectClassName1 = 50,
    DLL_RTI__RTIambassador__getObjectInstanceHandle1 = 51,
    DLL_RTI__RTIambassador__getObjectInstanceName1 = 52,
    DLL_RTI__RTIambassador__getOrderingHandle1 = 53,
    DLL_RTI__RTIambassador__getOrderingName1 = 54,
    DLL_RTI__RTIambassador__getParameterHandle2 = 55,
    DLL_RTI__RTIambassador__getParameterName2 = 56,
    DLL_RTI__RTIambassador__getRegion1 = 57,
    DLL_RTI__RTIambassador__getRegionToken1 = 58,
    DLL_RTI__RTIambassador__getRoutingSpaceHandle1 = 59,
    DLL_RTI__RTIambassador__getRoutingSpaceName1 = 60,
    DLL_RTI__RTIambassador__getTransportationHandle1 = 61,
    DLL_RTI__RTIambassador__getTransportationName1 = 62,
    DLL_RTI__RTIambassador__isAttributeOwnedByFederate2 = 63,
    DLL_RTI__RTIambassador__joinFederationExecution3 = 64,
    DLL_RTI__RTIambassador__localDeleteObjectInstance1 = 65,
    DLL_RTI__RTIambassador__modifyLookahead1 = 66,
    DLL_RTI__RTIambassador__negotiatedAttributeOwnershipDivestiture3 = 67,
    DLL_RTI__RTIambassador__nextEventRequest1 = 68,
    DLL_RTI__RTIambassador__nextEventRequestAvailable1 = 69,
    DLL_RTI__RTIambassador__notifyAboutRegionModification1 = 70,
    DLL_RTI__RTIambassador__publishInteractionClass1 = 71,
    DLL_RTI__RTIambassador__publishObjectClass2 = 72,
    DLL_RTI__RTIambassador__queryAttributeOwnership2 = 73,
    DLL_RTI__RTIambassador__queryFederateTime1 = 74,
    DLL_RTI__RTIambassador__queryLBTS1 = 75,
    DLL_RTI__RTIambassador__queryLookahead1 = 76,
    DLL_RTI__RTIambassador__queryMinNextEventTime1 = 77,
    DLL_RTI__RTIambassador__registerFederationSynchronizationPoint2 = 78,
    DLL_RTI__RTIambassador__registerFederationSynchronizationPoint3 = 79,
    DLL_RTI__RTIambassador__registerObjectInstance1 = 80,
    DLL_RTI__RTIambassador__registerObjectInstance2 = 81,
    DLL_RTI__RTIambassador__registerObjectInstanceWithRegion5 = 82,
    DLL_RTI__RTIambassador__registerObjectInstanceWithRegion4 = 83,
    DLL_RTI__RTIambassador__requestClassAttributeValueUpdate2 = 84,
    DLL_RTI__RTIambassador__requestClassAttributeValueUpdateWithRegion3 = 85,
    DLL_RTI__RTIambassador__requestFederationRestore1 = 86,
    DLL_RTI__RTIambassador__requestFederationSave1 = 87,
    DLL_RTI__RTIambassador__requestFederationSave2 = 88,
    DLL_RTI__RTIambassador__requestObjectAttributeValueUpdate2 = 89,
    DLL_RTI__RTIambassador__resignFederationExecution1 = 90,
    DLL_RTI__RTIambassador__retract1 = 91,
    DLL_RTI__RTIambassador__sendInteraction4 = 92,
    DLL_RTI__RTIambassador__sendInteraction3 = 93,
    DLL_RTI__RTIambassador__sendInteractionWithRegion5 = 94,
    DLL_RTI__RTIambassador__sendInteractionWithRegion4 = 95,
    DLL_RTI__RTIambassador__subscribeInteractionClass2 = 96,
    DLL_RTI__RTIambassador__subscribeInteractionClassWithRegion3 = 97,
    DLL_RTI__RTIambassador__subscribeObjectClassAttributes3 = 98,
    DLL_RTI__RTIambassador__subscribeObjectClassAttributesWithRegion4 = 99,
    DLL_RTI__RTIambassador__synchronizationPointAchieved1 = 100,
    DLL_RTI__RTIambassador__tick2 = 101,
    DLL_RTI__RTIambassador__tick0 = 102,
    DLL_RTI__RTIambassador__timeAdvanceRequest1 = 103,
    DLL_RTI__RTIambassador__timeAdvanceRequestAvailable1 = 104,
    DLL_RTI__RTIambassador__unassociateRegionForUpdates2 = 105,
    DLL_RTI__RTIambassador__unconditionalAttributeOwnershipDivestiture2 = 106,
    DLL_RTI__RTIambassador__unpublishInteractionClass1 = 107,
    DLL_RTI__RTIambassador__unpublishObjectClass1 = 108,
    DLL_RTI__RTIambassador__unsubscribeInteractionClass1 = 109,
    DLL_RTI__RTIambassador__unsubscribeInteractionClassWithRegion2 = 110,
    DLL_RTI__RTIambassador__unsubscribeObjectClass1 = 111,
    DLL_RTI__RTIambassador__unsubscribeObjectClassWithRegion2 = 112,
    DLL_RTI__RTIambassador__updateAttributeValues4 = 113,
    DLL_RTI__RTIambassador__updateAttributeValues3 = 114,
    DLL_RTI__RTIambassador__dummy = 115
};

